### ISSUE TITLE
Photon implementation

### ISSUE THREAD

**Issue by tbruyelle** [atomone-hub/atomone#44]
From the AtomOne Constitution [Article 3 Section 5](https://github.com/atomone-hub/genesis/blob/main/CONSTITUTION.md#section-5-the-photon-token)

> Section 5: The PHOTON Token
> The PHOTON shall be the only fee token except for ATONE to PHOTON burn transactions. This applies for all transactions on the root and core shards, and all IBC and ICS payments.
> 
> ATONE tokens may be burned to PHOTON tokens at a conversion rate set by law such that the total amount of PHOTONs mintable through burning ATONE tokens shall be capped at 1B PHOTON tokens.
> 
> PHOTONs cannot be converted back into ATONE tokens.

The implementation work will be splitted in multiple tasks, each possibly involving a different PR:

- [x] The photon ADR (#34) 
- [x] The photon mint message (#53)
- [x] The photon ante decorator (#54)
- [x] The photon denom metadata migration (#55)
- [x] Documentation about validator config and `minimum-gas-price` (#51)
